oauth: {}

action_mailer:
  default_options: {}
  default_url_options: {}
  smtp_settings: {}

mailers:
  single:
    to:
  digest:
    to:

slack:
  webhook_url:

feeds:
  - http://digital-scholarship.org/digitalkoans/category/digital-library-jobs/feed/

blocklist: []
