name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '*' ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.2']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Bundle install
      run: bundle config path vendor/bundle
    - name: Install dependencies
      run: bin/setup
    - name: Run tests
      run: bundle exec rake
